### ISSUE TITLE
Assignment 2 NEW plans

### ISSUE THREAD

**Issue by Thanh-8213** [etc5521-2020/assignment-1-hakea#5]
From Dr. Cook feedback, I crafted a new, improved version of our plan

Inadequacies of previous report:
 - Unclean data. There are missing values and abnormal values that need to be cleaned. For example:  Altitude of coffee farm has value of more them 10,000 m, which is physically impossible. 
- Poor plot design (Pie chart with hard-to-see color palette)
- Regression model suffered from multicollinear and outliers, which provide wrong/biased result.

Change to fix the inadequacies:
- Clean the data of outliers, produce a cleaner, less biased dataset
- Change the plot design to others type (Boxplot), to better understand and represent the data
- Re-run regression model with cleaner data, to produce a more accurate, non-biased result.

Research questions:  
We will tell a story of the quality of coffee, from the farm to the cup,
This will consist of: 
- Quality of coffee by country
- Quality of coffee by altitude
- Quality of coffee by process method 
- Quality of coffee by year (NEW)

However, as coffee doesn't have wings to fly to our cup,  it must be traded. We will discuss about Fair Trade. (NEW)

**Comment by rlin0004** [comment]
update on secondary questions:

1. Which country produces the best quality coffee beans, which regions perform better than others in the quality of the coffee beans produced, intra-country?

2. Using the regression model, explain how factors like altitude, processing method, and defects affect the quality of the beans produced.

3. Which countries perform best on individual grading criteria such as aroma, acidity, sweetness, etc?

4. The quality of coffee developed overtime. (NEW)

5. What is the common processing method of top-graded coffee beans, how different processing method behaves on the individual grading criteria of coffee? (NEW)
